<?php if (!defined('BASEPATH')) exit('No direct script access allowed');

class Migration_Injuries_data extends Migration {

    public function up()
	{
		$prefix = $this->db->dbprefix;

        // Injuries List
        $this->dbforge->add_field('`id` int(11) NOT NULL AUTO_INCREMENT');
        $this->dbforge->add_field("`injury_text` varchar(100) NOT NULL DEFAULT ''");
        $this->dbforge->add_key('id', true);
        $this->dbforge->create_table('list_injuries');

        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(1, 'bruised cheekbone')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(2, 'fractured cheekbone')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(3, 'swollen ear')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(4, 'blurred vision')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(5, 'eye irritation')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(6, 'scratched cornea')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(7, 'fractured eye socket')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(8, 'migraine')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(9, 'concussion')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(10, 'fractured skull')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(11, 'bruised jaw')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(12, 'fractured jaw')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(13, 'cold')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(14, 'bronchitis')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(15, 'strep throat')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(16, 'flu')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(17, 'bruised neck')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(18, 'neck stiffness')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(19, 'pinched nerve (neck)')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(20, 'broken nose')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(21, 'chipped tooth')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(22, 'bruised elbow')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(23, 'fractured ulna (arm)')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(24, 'tender elbow')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(25, 'hyperextended elbow')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(26, 'bone chips (elbow)')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(27, 'fractured elbow')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(28, 'finger blister')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(29, 'bruised finger')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(30, 'jammed finger')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(31, 'dislocated finger')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(32, 'fractured finger')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(33, 'bruised hand')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(34, 'fractured hand')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(35, 'broken hand')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(36, 'broken kneecap')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(37, 'broken bone in elbow')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(38, 'elbow strain')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(39, 'ruptured ulnar collateral ligament')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(40, 'strained bicep tendon')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(41, 'ruptured bicep tendon')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(42, 'strained tricep tendon')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(43, 'ruptured tricep tendon')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(44, 'biceps strain')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(45, 'torn biceps')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(46, 'strained triceps')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(47, 'torn triceps')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(48, 'rotator cuff strain')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(49, 'torn rotator cuff')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(50, 'tender shoulder')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(51, 'dislocated shoulder')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(52, 'bruised wrist')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(53, 'fractured wrist')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(54, 'back spasms')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(55, 'herniated disc (back)')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(56, 'ruptured disc (back)')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(57, 'bruised hip')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(58, 'fractured hip')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(59, 'mild abdominal strain')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(60, 'torn abdominal muscle')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(61, 'strained back')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(62, 'torn back muscle')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(63, 'strained rib cage muscle')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(64, 'torn rib cage muscle')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(65, 'strained groin')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(66, 'torn groin')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(67, 'hip flexor strain')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(68, 'torn hip flexor tendon')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(69, 'bruised ribs')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(70, 'fractured rib')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(71, 'bruised ankle')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(72, 'sprained ankle')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(73, 'fractured ankle')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(74, 'bruised foot')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(75, 'fractured foot')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(76, 'bruised heel')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(77, 'sore knee')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(78, 'hyperextended knee')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(79, 'fractured knee')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(80, 'strained Achilles tendon')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(81, 'ruptured Achilles tendon')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(82, 'strained anterior cruciate ligament')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(83, 'torn anterior cruciate ligament')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(84, 'strained posterior cruciate ligament')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(85, 'torn posterior cruciate ligament')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(86, 'strained medial collateral ligament')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(87, 'ruptured medial collateral ligament')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(88, 'calf strain')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(89, 'torn calf muscle')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(90, 'strained hamstring')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(91, 'torn hamstring')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(92, 'thigh muscle strain')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(93, 'torn thigh muscle')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(94, 'torn ankle ligaments')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(95, 'torn meniscus (knee)')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(96, 'sports hernia')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(97, 'torn labrum (Shoulder)')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(98, 'dead arm')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(99, 'undisclosed injury')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(100, 'pulled abdominal muscle')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(101, 'abdominal soreness')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(102, 'strained abdominal muscle')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(103, 'acromioclavicular joint irritation')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(104, 'sore Achilles tendon')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(105, 'adductor strain')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(106, 'allergic reaction')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(107, 'sore ankle')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(108, 'ankle soreness')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(109, 'appendectomy')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(110, 'arthritic elbow')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(111, 'asthma')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(112, 'sore back')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(113, 'back soreness')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(114, 'chronic back soreness')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(115, 'recurring back spasms')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(116, 'back stiffness')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(117, 'back tightness')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(118, 'bone bruise (knee)')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(119, 'bone bruise (wrist)')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(120, 'surgery to remove bone chips (elbow)')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(121, 'bone edema (wrist)')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(122, 'bone spur (elbow)')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(123, 'surgery to remove bone spur (elbow)')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(124, 'broken hamate bone')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(125, 'elbow contusion')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(126, 'bruised back')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(127, 'bruised calf')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(128, 'bruised collarbone')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(129, 'bruised forearm')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(130, 'bruised forehead')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(131, 'bruised finger')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(132, 'bruised knee')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(133, 'knee contusion')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(134, 'bruised lung')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(135, 'bruised shin')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(136, 'bruised shoulder')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(137, 'bruised thigh')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(138, 'bruised thumb')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(139, 'thumb contusion')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(140, 'bruised toe')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(141, 'hand contusion')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(142, 'foot contusion')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(143, 'Buerger''s Disease')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(144, 'calf cramp')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(145, 'calf soreness')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(146, 'mild calf strain')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(147, 'colitis')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(148, 'conjunctivitis')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(149, 'dehydration')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(150, 'diverticulitis')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(151, 'dizziness and nausea')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(152, 'earache')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(153, 'elbow inflammation')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(154, 'sore elbow')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(155, 'elbow soreness')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(156, 'acute elbow soreness')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(157, 'elbow tendinitis')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(158, 'eye infection')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(159, 'fever')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(160, 'esophageal spasms')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(161, 'finger infection')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(162, 'flu-like symptoms')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(163, 'food poisoning')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(164, 'gastroenteritis')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(165, 'gout')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(166, 'heart palpitations')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(167, 'intestinal virus')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(168, 'inner ear infection')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(169, 'kidney stones')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(170, 'nausea')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(171, 'pleurisy')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(172, 'sinus infection')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(173, 'sinusitis')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(174, 'viral infection')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(175, 'stomach virus')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(176, 'upper respiratory infection')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(177, 'virus')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(178, 'thoracic outlet syndrome')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(179, 'torn fingernail')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(180, 'finger avulsion')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(181, 'flexor-pronator strain (elbow)')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(182, 'foot soreness')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(183, 'strained foot')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(184, 'forearm cramp')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(185, 'forearm inflammation')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(186, 'forearm soreness')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(187, 'forearm stiffness')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(188, 'strained forearm')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(189, 'forearm tendinitis')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(190, 'fractured coracoid (shoulder)')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(191, 'biceps tendinitis')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(192, 'triceps strain')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(193, 'fractured fibula')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(194, 'fractured shoulder blade')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(195, 'fractured thumb')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(196, 'fractured tibia')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(197, 'gluteus strain')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(198, 'groin soreness')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(199, 'sore groin')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(200, 'mild groin strain')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(201, 'groin tightness')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(202, 'hamstring cramp')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(203, 'hamstring soreness')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(204, 'sore hamstring')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(205, 'hamstring spasms')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(206, 'hamstring strain')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(207, 'mild hamstring strain')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(208, 'hamstring tendinitis')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(209, 'hamstring tightness')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(210, 'hand soreness')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(211, 'heat exhaustion')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(212, 'heel soreness')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(213, 'herniated disc (neck)')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(214, 'high ankle sprain')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(215, 'hip soreness')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(216, 'mild hip strain')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(217, 'hip strain')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(218, 'hyperextended ankle')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(219, 'inflamed facet joints (neck)')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(220, 'intercostal strain')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(221, 'knee inflammation')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(222, 'knee soreness')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(223, 'knee tendinitis')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(224, 'lacerated chin')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(225, 'lacerated finger')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(226, 'lacerated hand')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(227, 'lacerated shin')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(228, 'latissimus dorsi strain')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(229, 'microfracture surgery (knee)')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(230, 'neck spasms')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(231, 'oblique strain')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(232, 'strained oblique')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(233, 'mild oblique strain')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(234, 'patellar tendinitis')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(235, 'plantar fascitis')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(236, 'post-concussion syndrome')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(237, 'posterior cruciate ligament strain (knee)')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(238, 'precautionary reasons (head injury)')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(239, 'quadriceps soreness')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(240, 'quadriceps strain')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(241, 'strained quadriceps')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(242, 'radial nerve (elbow) decompression surgery')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(243, 'rotator cuff inflammation')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(244, 'rotator cuff tendinitis')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(245, 'ruptured tendon (finger)')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(246, 'ruptured tendon (foot)')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(247, 'separated shoulder')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(248, 'shin splints')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(249, 'shoulder bursitis')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(250, 'shoulder impingement')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(251, 'mild shoulder inflammation')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(252, 'shoulder inflammation')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(253, 'shoulder soreness')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(254, 'sore shoulder')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(255, 'mild shoulder strain')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(256, 'strained shoulder')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(257, 'shoulder subluxation')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(258, 'shoulder surgery (scar tissue)')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(259, 'shoulder tendinitis')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(260, 'sprained acromioclavicular joint')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(261, 'sprained elbow')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(262, 'sprained finger')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(263, 'sprained knee')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(264, 'sprained thumb')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(265, 'sprained ulnar collateral ligament (elbow)')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(266, 'sprained wrist')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(267, 'sore thumb')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(268, 'tired arm')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(269, 'torn elbow ligament')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(270, 'elbow ligament reconstruction surgery')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(271, 'torn UCL (Tommy John surgery)')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(272, 'partially torn UCL (Tommy John surgery)')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(273, 'torn flexor tendon (elbow)')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(274, 'partially torn labrum')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(275, 'torn plantar fascia tendon')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(276, 'torn posterior cruciate ligament (knee)')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(277, 'torn quadriceps')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(278, 'torn thumb ligament')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(279, 'partially torn ulnar collateral ligament (elbow)')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(280, 'triceps tendinitis')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(281, 'twisted ankle')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(282, 'ulnar nerve irritation')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(283, 'whiplash')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(284, 'wrist soreness')");
        $this->db->query("INSERT INTO {$prefix}list_injuries VALUES(285, 'wrist tendinitis')");
	}
	
	//--------------------------------------------------------------------
	
	public function down() 
	{
		$prefix = $this->db->dbprefix;

        $this->dbforge->drop_table('list_injuries');
	}
	
	//--------------------------------------------------------------------
	
}